### ISSUE TITLE
Evaluating a model with a simplex parameter type gives segmentation fault

### ISSUE THREAD

**Issue by alecksphillips** [roualdes/bridgestan#38]
When evaluating the density of a model containing a simplex parameter, bridgestan gives a seg fault:

```
import bridgestan as bs
import numpy as np
model = bs.StanModel.from_stan_file("../test_models/simplex/simplex.stan")
param_length = model.param_num()
theta = np.array([1/param_length] * param_length)
theta_unc = model.param_unconstrain(theta)
log_p = model.log_density(theta_unc)
```

Output:
```
[1]    12697 segmentation fault (core dumped)  /usr/bin/python
```

The same occurs with the R interface.

As a side note, the model in `test_models/simplex/simplex.stan` had a misspecified prior which I've fixed in #37

**Comment by WardBrian** [comment]
I can't recreate this, running the same example for me yields 
```
>>> log_p
-16.094379124341003
```

Can you share some information about your system/environment, python versions, etc?

**Comment by WardBrian** [comment]
Hm, my setup is CmdStan 2.30.1, Ubuntu 20.04, gcc 9.40, python 3.9.13

Do you have any environment variables (or changes to `$cmdstan/make/local`) which would affect compilation? CXXFLAGS etc

**Comment by alecksphillips** [comment]
Can't find anything that looks like it would affect compilation.

Just tried on a Ubuntu 20.04 install with gcc/g++ 9.4.0 and python 3.9.5 (built with gcc 9.3.0) which works fine. Later versions of gcc to blame?

**Comment by WardBrian** [comment]
That would be a bummer if GCC broke something here. If you're willing to give some more time to debugging this, it would be great to get a full backtrace out of the core dump python produces, to see if it's anything we could fix easily

**Comment by alecksphillips** [comment]
Output from gdb on Ubuntu 22.04.1 with gcc 11.2.0 (easier to get python debug symbols than on arch):
```
(gdb) bt
#0  0x00007fffeb7369eb in stan::math::internal::reverse_pass_callback_vari<stan::math::simplex_constrain<Eigen::Map<Eigen::Matrix<stan::math::var_value<double, void>, -1, 1, 0, -1, 1>, 0, Eigen::Stride<0, 0> >, (void*)0>(Eigen::Map<Eigen::Matrix<stan::math::var_value<double, void>, -1, 1, 0, -1, 1>, 0, Eigen::Stride<0, 0> > const&, stan::scalar_type<Eigen::Map<Eigen::Matrix<stan::math::var_value<double, void>, -1, 1, 0, -1, 1>, 0, Eigen::Stride<0, 0> >, void>::type&)::{lambda()#1}>::chain() () from /home/alecks/git/bridgestan/test_models/simplex/simplex_model.so
#1  0x00007fffeb75b73f in void stan::math::gradient<model_functor<stan::model::model_base*> >(model_functor<stan::model::model_base*> const&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&, double&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&) () from /home/alecks/git/bridgestan/test_models/simplex/simplex_model.so
#2  0x00007fffeb74d217 in model_rng::log_density(bool, bool, double const*, double*) () from /home/alecks/git/bridgestan/test_models/simplex/simplex_model.so
#3  0x00007fffeb74d532 in log_density () from /home/alecks/git/bridgestan/test_models/simplex/simplex_model.so
#4  0x00007ffff6982e2e in ?? () from /lib/x86_64-linux-gnu/libffi.so.8
#5  0x00007ffff697f493 in ?? () from /lib/x86_64-linux-gnu/libffi.so.8
#6  0x00007ffff6bed451 in _call_function_pointer (argtypecount=<optimised out>, argcount=5, resmem=0x7fffffffd660, restype=<optimised out>, atypes=<optimised out>, avalues=<optimised out>, pProc=0x7fffeb74d520 <log_density>, 
    flags=4353) at ./Modules/_ctypes/callproc.c:916
#7  _ctypes_callproc (pProc=<optimised out>, argtuple=<optimised out>, flags=<optimised out>, argtypes=<optimised out>, restype=<optimised out>, checker=<optimised out>) at ./Modules/_ctypes/callproc.c:1259
#8  0x00007ffff6bf6ce2 in PyCFuncPtr_call (self=<optimised out>, inargs=<optimised out>, kwds=0x0) at ./Modules/_ctypes/_ctypes.c:4201
#9  0x00005555556a73bb in _PyObject_MakeTpCall (tstate=0x555555b5ca60, callable=<_FuncPtr(__name__='log_density') at remote 0x7ffff3bc3a00>, args=<optimised out>, nargs=<optimised out>, keywords=0x0) at ../Objects/call.c:215
#10 0x000055555569ff59 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimised out>, args=<optimised out>, callable=<_FuncPtr(__name__='log_density') at remote 0x7ffff3bc3a00>, tstate=<optimised out>)
    at ../Include/cpython/abstract.h:112
#11 _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimised out>, args=0x7ffff41c2940, callable=<_FuncPtr(__name__='log_density') at remote 0x7ffff3bc3a00>, tstate=<optimised out>) at ../Include/cpython/abstract.h:99
#12 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimised out>, args=0x7ffff41c2940, callable=<_FuncPtr(__name__='log_density') at remote 0x7ffff3bc3a00>) at ../Include/cpython/abstract.h:123
#13 call_function (kwnames=0x0, oparg=<optimised out>, pp_stack=<synthetic pointer>, trace_info=0x7fffffffda40, tstate=<optimised out>) at ../Python/ceval.c:5891
#14 _PyEval_EvalFrameDefault (tstate=<optimised out>, f=<optimised out>, throwflag=<optimised out>) at ../Python/ceval.c:4181
#15 0x00005555556b112c in _PyEval_EvalFrame (throwflag=0, 
    f=Frame 0x7ffff41c27a0, for file /home/alecks/git/bridgestan/python/bridgestan/model.py, line 386, in log_density (self=<StanModel(lib_path='/home/alecks/git/bridgestan/test_models/simplex/simplex_model.so', stanlib=<CDLL(_name='/home/alecks/git/bridgestan/test_models/simplex/simplex_model.so', _FuncPtr=<_ctypes.PyCFuncPtrType at remote 0x55555600b0f0>, _handle=93825003467936, construct=<_FuncPtr(__name__='construct') at remote 0x7ffff3bc3340>, name=<_FuncPtr(__name__='name') at remote 0x7ffff3bc3400>, param_num=<_FuncPtr(__name__='param_num') at remote 0x7ffff3bc34c0>, param_unc_num=<_FuncPtr(__name__='param_unc_num') at remote 0x7ffff3bc3580>, param_names=<_FuncPtr(__name__='param_names') at remote 0x7ffff3bc3640>, param_unc_names=<_FuncPtr(__name__='param_unc_names') at remote 0x7ffff3bc3700>, param_constrain=<_FuncPtr(__name__='param_constrain') at remote 0x7ffff3bc37c0>, param_unconstrain=<_FuncPtr(__name__='param_unconstrain') at remote 0x7ffff3bc3880>, param_unconstrain_json=<_FuncPtr(__name__='param_unc...(truncated), tstate=0x555555b5ca60) at ../Include/internal/pycore_ceval.h:46
#16 _PyEval_Vector (kwnames=<optimised out>, argcount=<optimised out>, args=<optimised out>, locals=0x0, con=0x7fffeb7c07a0, tstate=0x555555b5ca60) at ../Python/ceval.c:5065
#17 _PyFunction_Vectorcall (func=<function at remote 0x7fffeb7c0790>, stack=<optimised out>, nargsf=<optimised out>, kwnames=<optimised out>) at ../Objects/call.c:342
#18 0x00005555556999e6 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimised out>, args=0x7ffff6d91da8, callable=<function at remote 0x7fffeb7c0790>, tstate=0x555555b5ca60) at ../Include/cpython/abstract.h:114
#19 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimised out>, args=0x7ffff6d91da8, callable=<function at remote 0x7fffeb7c0790>) at ../Include/cpython/abstract.h:123
#20 call_function (kwnames=0x0, oparg=<optimised out>, pp_stack=<synthetic pointer>, trace_info=0x7fffffffdc10, tstate=<optimised out>) at ../Python/ceval.c:5891
#21 _PyEval_EvalFrameDefault (tstate=<optimised out>, f=<optimised out>, throwflag=<optimised out>) at ../Python/ceval.c:4198
#22 0x0000555555696026 in _PyEval_EvalFrame (throwflag=0, f=Frame 0x7ffff6d91c40, for file /home/alecks/git/bridgestan/python/simplex_test.py, line 12, in <module> (), tstate=0x555555b5ca60)
    at ../Include/internal/pycore_ceval.h:46
#23 _PyEval_Vector (tstate=0x555555b5ca60, con=<optimised out>, locals=<optimised out>, args=<optimised out>, argcount=<optimised out>, kwnames=<optimised out>) at ../Python/ceval.c:5065
#24 0x000055555578c106 in PyEval_EvalCode (co=<code at remote 0x7ffff6c473c0>, 
    globals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='/home/alecks/git/bridgestan/python/simplex_test.py') at remote 0x7ffff6c2d2a0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff6df85e0>, '__file__': '/home/alecks/git/bridgestan/python/simplex_test.py', '__cached__': None, 'bs': <module at remote 0x7ffff6c87920>, 'np': <module at remote 0x7ffff69b7a10>, 'model': <StanModel(lib_path='/home/alecks/git/bridgestan/test_models/simplex/simplex_model.so', stanlib=<CDLL(_name='/home/alecks/git/bridgestan/test_models/simplex/simplex_model.so', _FuncPtr=<_ctypes.PyCFuncPtrType at remote 0x55555600b0f0>, _handle=93825003467936, construct=<_FuncPtr(__name__='construct') at remote 0x7ffff3bc3340>, name=<_FuncPtr(__name__='name') at remote 0x7ffff3bc3400>, param_num=<_FuncPtr(__name__='param_num') at remote 0x7ffff3bc34c0>, param_unc_num=<_FuncPtr(__name__='param_unc_num') at remote 0x7ffff3bc3580>, param_names=<_FuncPtr(_...(truncated), locals=<optimised out>) at ../Python/ceval.c:1134
#25 0x00005555557b8e18 in run_eval_code_obj (tstate=0x555555b5ca60, co=0x7ffff6c473c0, 
    globals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='/home/alecks/git/bridgestan/python/simplex_test.py') at remote 0x7ffff6c2d2a0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff6df85e0>, '__file__': '/home/alecks/git/bridgestan/python/simplex_test.py', '__cached__': None, 'bs': <module at remote 0x7ffff6c87920>, 'np': <module at remote 0x7ffff69b7a10>, 'model': <StanModel(lib_path='/home/alecks/git/bridgestan/test_models/simplex/simplex_model.so', stanlib=<CDLL(_name='/home/alecks/git/bridgestan/test_models/simplex/simplex_model.so', _FuncPtr=<_ctypes.PyCFuncPtrType at remote 0x55555600b0f0>, _handle=93825003467936, construct=<_FuncPtr(__name__='construct') at remote 0x7ffff3bc3340>, name=<_FuncPtr(__name__='name') at remote 0x7ffff3bc3400>, param_num=<_FuncPtr(__name__='param_num') at remote 0x7ffff3bc34c0>, param_unc_num=<_FuncPtr(__name__='param_unc_num') at remote 0x7ffff3bc3580>, param_names=<_FuncPtr(_...(truncated), 
    locals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='/home/alecks/git/bridgestan/python/simplex_test.py') at remote 0x7ffff6c2d2a0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff6df85e0>, '__file__': '/home/alecks/git/bridgestan/python/simplex_test.py', '__cached__': None, 'bs': <module at remote 0x7ffff6c87920>, 'np': <module at remote 0x7ffff69b7a10>, 'model': <StanModel(lib_path='/home/alecks/git/bridgestan/test_models/simplex/simplex_model.so', stanlib=<CDLL(_name='/home/alecks/git/bridgestan/test_models/simplex/simplex_model.so', _FuncPtr=<_ctypes.PyCFuncPtrType at remote 0x55555600b0f0>, _handle=93825003467936, construct=<_FuncPtr(__name__='construct') at remote 0x7ffff3bc3340>, name=<_FuncPtr(__name__='name') at remote 0x7ffff3bc3400>, param_num=<_FuncPtr(__name__='param_num') at remote 0x7ffff3bc34c0>, param_unc_num=<_FuncPtr(__name__='param_unc_num') at remote 0x7ffff3bc3580>, param_names=<_FuncPtr(_...(truncated)) at ../Python/pythonrun.c:1291
#26 0x00005555557b1c6b in run_mod (mod=<optimised out>, filename=<optimised out>, 
    globals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='/home/alecks/git/bridgestan/python/simplex_test.py') at remote 0x7ffff6c2d2a0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff6df85e0>, '__file__': '/home/alecks/git/bridgestan/python/simplex_test.py', '__cached__': None, 'bs': <module at remote 0x7ffff6c87920>, 'np': <module at remote 0x7ffff--Type <RET> for more, q to quit, c to continue without paging--
69b7a10>, 'model': <StanModel(lib_path='/home/alecks/git/bridgestan/test_models/simplex/simplex_model.so', stanlib=<CDLL(_name='/home/alecks/git/bridgestan/test_models/simplex/simplex_model.so', _FuncPtr=<_ctypes.PyCFuncPtrType at remote 0x55555600b0f0>, _handle=93825003467936, construct=<_FuncPtr(__name__='construct') at remote 0x7ffff3bc3340>, name=<_FuncPtr(__name__='name') at remote 0x7ffff3bc3400>, param_num=<_FuncPtr(__name__='param_num') at remote 0x7ffff3bc34c0>, param_unc_num=<_FuncPtr(__name__='param_unc_num') at remote 0x7ffff3bc3580>, param_names=<_FuncPtr(_...(truncated), 
    locals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='/home/alecks/git/bridgestan/python/simplex_test.py') at remote 0x7ffff6c2d2a0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff6df85e0>, '__file__': '/home/alecks/git/bridgestan/python/simplex_test.py', '__cached__': None, 'bs': <module at remote 0x7ffff6c87920>, 'np': <module at remote 0x7ffff69b7a10>, 'model': <StanModel(lib_path='/home/alecks/git/bridgestan/test_models/simplex/simplex_model.so', stanlib=<CDLL(_name='/home/alecks/git/bridgestan/test_models/simplex/simplex_model.so', _FuncPtr=<_ctypes.PyCFuncPtrType at remote 0x55555600b0f0>, _handle=93825003467936, construct=<_FuncPtr(__name__='construct') at remote 0x7ffff3bc3340>, name=<_FuncPtr(__name__='name') at remote 0x7ffff3bc3400>, param_num=<_FuncPtr(__name__='param_num') at remote 0x7ffff3bc34c0>, param_unc_num=<_FuncPtr(__name__='param_unc_num') at remote 0x7ffff3bc3580>, param_names=<_FuncPtr(_...(truncated), flags=<optimised out>, arena=<optimised out>) at ../Python/pythonrun.c:1312
#27 0x00005555557b8b65 in pyrun_file (fp=fp@entry=0x555555b5ee30, filename=filename@entry='/home/alecks/git/bridgestan/python/simplex_test.py', start=start@entry=257, 
    globals=globals@entry={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='/home/alecks/git/bridgestan/python/simplex_test.py') at remote 0x7ffff6c2d2a0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff6df85e0>, '__file__': '/home/alecks/git/bridgestan/python/simplex_test.py', '__cached__': None, 'bs': <module at remote 0x7ffff6c87920>, 'np': <module at remote 0x7ffff69b7a10>, 'model': <StanModel(lib_path='/home/alecks/git/bridgestan/test_models/simplex/simplex_model.so', stanlib=<CDLL(_name='/home/alecks/git/bridgestan/test_models/simplex/simplex_model.so', _FuncPtr=<_ctypes.PyCFuncPtrType at remote 0x55555600b0f0>, _handle=93825003467936, construct=<_FuncPtr(__name__='construct') at remote 0x7ffff3bc3340>, name=<_FuncPtr(__name__='name') at remote 0x7ffff3bc3400>, param_num=<_FuncPtr(__name__='param_num') at remote 0x7ffff3bc34c0>, param_unc_num=<_FuncPtr(__name__='param_unc_num') at remote 0x7ffff3bc3580>, param_names=<_FuncPtr(_...(truncated), 
    locals=locals@entry={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='/home/alecks/git/bridgestan/python/simplex_test.py') at remote 0x7ffff6c2d2a0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff6df85e0>, '__file__': '/home/alecks/git/bridgestan/python/simplex_test.py', '__cached__': None, 'bs': <module at remote 0x7ffff6c87920>, 'np': <module at remote 0x7ffff69b7a10>, 'model': <StanModel(lib_path='/home/alecks/git/bridgestan/test_models/simplex/simplex_model.so', stanlib=<CDLL(_name='/home/alecks/git/bridgestan/test_models/simplex/simplex_model.so', _FuncPtr=<_ctypes.PyCFuncPtrType at remote 0x55555600b0f0>, _handle=93825003467936, construct=<_FuncPtr(__name__='construct') at remote 0x7ffff3bc3340>, name=<_FuncPtr(__name__='name') at remote 0x7ffff3bc3400>, param_num=<_FuncPtr(__name__='param_num') at remote 0x7ffff3bc34c0>, param_unc_num=<_FuncPtr(__name__='param_unc_num') at remote 0x7ffff3bc3580>, param_names=<_FuncPtr(_...(truncated), closeit=closeit@entry=1, flags=0x7fffffffdeb8) at ../Python/pythonrun.c:1208
#28 0x00005555557b8048 in _PyRun_SimpleFileObject (fp=0x555555b5ee30, filename='/home/alecks/git/bridgestan/python/simplex_test.py', closeit=1, flags=0x7fffffffdeb8) at ../Python/pythonrun.c:456
#29 0x00005555557b7d43 in _PyRun_AnyFileObject (fp=0x555555b5ee30, filename='/home/alecks/git/bridgestan/python/simplex_test.py', closeit=1, flags=0x7fffffffdeb8) at ../Python/pythonrun.c:90
#30 0x00005555557a917e in pymain_run_file_obj (skip_source_first_line=0, filename='/home/alecks/git/bridgestan/python/simplex_test.py', program_name='/usr/bin/python3') at ../Modules/main.c:353
#31 pymain_run_file (config=0x555555b40f60) at ../Modules/main.c:372
#32 pymain_run_python (exitcode=0x7fffffffdeb4) at ../Modules/main.c:587
#33 Py_RunMain () at ../Modules/main.c:666
#34 0x000055555577f0dd in Py_BytesMain (argc=<optimised out>, argv=<optimised out>) at ../Modules/main.c:720
#35 0x00007ffff7c79d90 in __libc_start_call_main (main=main@entry=0x55555577f0a0 <main>, argc=argc@entry=2, argv=argv@entry=0x7fffffffe0c8) at ../sysdeps/nptl/libc_start_call_main.h:58
#36 0x00007ffff7c79e40 in __libc_start_main_impl (main=0x55555577f0a0 <main>, argc=2, argv=0x7fffffffe0c8, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fffffffe0b8)
    at ../csu/libc-start.c:392
#37 0x000055555577efd5 in _start ()
```

Apologies if that's not what you meant

**Comment by WardBrian** [comment]
No that’s exactly what I wanted, sadly it doesn’t point me toward anything too specific.  We recently changed some of the code mentioned there in #41. If you git pull and rebuild does the segfault still occur?

**Comment by alecksphillips** [comment]
Segfault is gone! How strange.

Thanks!

**Comment by WardBrian** [comment]
I think we had some very subtle UB in our memory management before that PR, which maybe later versions of GCC brought out. Glad it’s fixed!
